#!/usr/bin/env python3
"""Tools/StubCompile/generate_stubs.py -- emit an empty `<Header>.generated.h` for every header under Source/.

This is part of the StubCompile MODEL TEST (see README.md), not a build step. UnrealHeaderTool generates real
`.generated.h` files with reflection data; here each one is an empty placeholder so that the `#include
"<Header>.generated.h"` line (which UHT requires to be the last include of a reflected header) resolves under clang.

Usage: python3 Tools/StubCompile/generate_stubs.py [--source DIR] [--out DIR]
Prints the number of files written. Existing files are rewritten only when their content would change, so the
directory is safe to keep between runs. Stale files for headers that no longer exist are removed.
"""

import argparse
import os
import sys

TEMPLATE = (
    "// Tools/StubCompile -- EMPTY stand-in for UnrealHeaderTool's {name}.generated.h (model test only; see README.md).\n"
    "// Generated by Tools/StubCompile/generate_stubs.py from Source/{rel}. Do not edit; do not commit.\n"
    "#pragma once\n"
)


def main() -> int:
    here = os.path.dirname(os.path.abspath(__file__))
    repo = os.path.abspath(os.path.join(here, os.pardir, os.pardir))
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--source", default=os.path.join(repo, "Source"), help="Source tree to scan (default: <repo>/Source)")
    parser.add_argument("--out", default=os.path.join(here, "generated"), help="Output directory (default: Tools/StubCompile/generated)")
    args = parser.parse_args()

    if not os.path.isdir(args.source):
        print(f"generate_stubs: source directory not found: {args.source}", file=sys.stderr)
        return 2

    os.makedirs(args.out, exist_ok=True)

    wanted = {}
    for root, _dirs, files in os.walk(args.source):
        for filename in sorted(files):
            if not filename.endswith(".h"):
                continue
            name = filename[:-2]
            rel = os.path.relpath(os.path.join(root, filename), args.source).replace(os.sep, "/")
            generated_name = f"{name}.generated.h"
            if generated_name in wanted:
                # Two headers with the same basename would collide in UHT too (it keys generated files by header name).
                print(f"generate_stubs: WARNING duplicate header basename {filename}: {wanted[generated_name]} and {rel}", file=sys.stderr)
            wanted[generated_name] = rel

    written = 0
    for generated_name, rel in sorted(wanted.items()):
        content = TEMPLATE.format(name=generated_name[: -len(".generated.h")], rel=rel)
        path = os.path.join(args.out, generated_name)
        try:
            with open(path, "r", encoding="utf-8") as existing:
                if existing.read() == content:
                    continue
        except FileNotFoundError:
            pass
        with open(path, "w", encoding="utf-8") as out:
            out.write(content)
        written += 1

    removed = 0
    for filename in os.listdir(args.out):
        if filename.endswith(".generated.h") and filename not in wanted:
            os.remove(os.path.join(args.out, filename))
            removed += 1

    print(f"generate_stubs: {len(wanted)} generated.h stubs in {os.path.relpath(args.out, repo)} ({written} written, {removed} stale removed)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
