// Project Ascension -- native Gameplay Tag declarations (charter Section 11.2, Appendix C).

#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

/**
 * Every Gameplay Tag the project uses, declared natively so C++ can reference them without string lookups.
 * Charter Section 11.2: tags drive systems, conditions, natures, states, Mantra conditions, Dao resonance and events;
 * Appendix C fixes the root `Ascension.` and its children (System, Qi.Condition, Qi.Nature, State, Event, Mantra, Dao,
 * Resonance, Scar). The same strings are listed in Config/DefaultGameplayTags.ini so the editor shows them before the
 * module loads. Definitions (with one-line meanings) live in AscensionGameplayTags.cpp.
 *
 * Variable naming: the tag string minus the `Ascension.` root, with `.` replaced by `_`
 * (e.g. `Ascension.State.Wisp.Drawn` -> `AscensionTags::State_Wisp_Drawn`).
 */
namespace AscensionTags
{
	// Ascension.System.* -- systems unlocked per Realm (charter 6.2, 11.2). A system whose tag is not unlocked is neither shown nor simulated.
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(System_Circulation);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(System_Pulse);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(System_Stability);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(System_BasicMantra);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(System_Purity);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(System_RefinementPulse);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(System_DantianCapacity);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(System_DaoUnlock);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(System_DensityLayers);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(System_SecondMantraChoice);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(System_DaoInsight);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(System_AnchorDrift);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(System_Core);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(System_CirculationMomentum);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(System_Keystone);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(System_SplitCirculation);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(System_AutoFullEfficiency);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(System_ThirdMantraChoice);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(System_CorruptedQi);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(System_DevouringMantra);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(System_DaoExpression);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(System_Domain);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(System_RealmWaveLayers);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(System_DualMantra);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(System_SecondKeystone);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(System_DaoResonance);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(System_AscensionPulse);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(System_FinalDaoNodes);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(System_Endgame);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(System_Breakthrough);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(System_Tribulation);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(System_AutoCultivation);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(System_Techniques);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(System_LayerModifier);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(System_DebugOverlay);

	// Ascension.Qi.Condition.* -- behavioural identities of Qi (charter 7.5).
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Qi_Condition_Pure);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Qi_Condition_Impure);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Qi_Condition_Corrupted);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Qi_Condition_Refined);

	// Ascension.Qi.Nature.* -- natures with one data-defined trait each (charter 7.6).
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Qi_Nature_Generic);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Qi_Nature_Fire);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Qi_Nature_Water);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Qi_Nature_Wood);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Qi_Nature_Metal);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Qi_Nature_Earth);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Qi_Nature_Yin);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Qi_Nature_Yang);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Qi_Nature_Life);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Qi_Nature_Void);

	// Ascension.State.* -- aura, player, and wisp states published for Mantra conditions and UI (charter 7.1-7.12, 9.1, D-0013).
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_InWorld);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Meditating);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Circulating_CW);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Circulating_CCW);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_CirculationHeld);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Pulse_Charging);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Pulse_Overcharging);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Pulse_Releasing);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Pulse_Recovering);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Pulse_Refining);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Breakthrough_Charging);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Breakthrough_Cooldown);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Tribulation_Warning);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Tribulation_Trial);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Tribulation_Resolution);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Backlash);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_BacklashRecovery);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_QiDeviation);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_AutoCultivating);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Corrupted);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_CoreCracked);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_DomainActive);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_ResonanceActive);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Layer_Early);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Layer_Middle);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Layer_Late);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Layer_Peak);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Stability_High);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Stability_Low);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Stability_Critical);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Purity_High);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Purity_Low);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Density_InnerOverDense);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Wisp_Free);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Wisp_Drawn);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Wisp_Absorbing);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Wisp_Absorbed);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Wisp_Rejected);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Wisp_Refining);

	// Ascension.Event.* -- the last-20 event log and the determinism checksum (charter 10.6, 11.3).
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_EnterMeditation);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_ExitMeditation);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_CirculationStarted);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_CirculationHeld);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_PulseCharged);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_PulseReleased);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_PulseOvercharged);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_RefinementPulse);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_WispSpawned);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_WispDrawn);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_WispSettled);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Absorbed);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Rejected);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Refined);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Transformed);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_BreakthroughAttempt);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_BreakthroughSuccess);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_BreakthroughFailure);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_TribulationStart);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_TribulationSurge);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_TribulationSuccess);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_TribulationFailure);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_MajorBreakthrough);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_RealmAdvance);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Backlash);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_QiDeviation);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_ScarCleared);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_CoreCracked);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_CoreRepaired);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_CorruptionApplied);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_CorruptionCleansed);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_ResonanceOverload);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_TechniqueUsed);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_InsightGranted);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_AutoToggled);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Saved);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Loaded);

	// Ascension.Mantra.* -- the eight Mantras and the Realm 8 conflict families (charter 9.1, 9.2).
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Mantra_Basic);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Mantra_Stillness);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Mantra_HeavenlyLight);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Mantra_FireGod);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Mantra_YinYang);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Mantra_DemonicDevouring);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Mantra_VoidStillness);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Mantra_Integration);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Mantra_Conflict_Aggressive);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Mantra_Conflict_Still);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Mantra_Conflict_Demonic);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Mantra_Conflict_Void);

	// Ascension.Dao.* -- the five Daos, node families, Techniques and Keystones (charter 9.3, 9.4, D-0014).
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Dao_Fire);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Dao_Water);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Dao_Life);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Dao_Sword);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Dao_Void);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Dao_Node_Technique);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Dao_Node_Expression);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Dao_Node_Principle);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Dao_Node_Insight);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Dao_Node_Keystone);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Dao_Technique_EmberPulse);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Dao_Technique_FlameCirculation);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Dao_Technique_StillPool);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Dao_Technique_Tide);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Dao_Technique_Bloom);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Dao_Technique_Cleanse);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Dao_Technique_Cut);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Dao_Technique_Edge);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Dao_Technique_Expand);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Dao_Technique_Silence);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Dao_Keystone_FurnaceHeart);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Dao_Keystone_DeepCurrent);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Dao_Keystone_Rooted);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Dao_Keystone_SingleStroke);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Dao_Keystone_Boundless);

	// Ascension.Resonance.* -- Dao resonance families and the Overload meter (charter 9.5).
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Resonance_Flame);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Resonance_Flow);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Resonance_Growth);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Resonance_Edge);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Resonance_Emptiness);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Resonance_Overload);

	// Ascension.Scar.* -- persistent failure states (charter 7.12, 7.5).
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Scar_Deviation);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Scar_BacklashInjury);
	ASCENSION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Scar_Corruption);
}
