// Project Ascension -- native Gameplay Tag definitions (charter Section 11.2, Appendix C).

#include "AscensionGameplayTags.h"

namespace AscensionTags
{
	// Ascension.System.* -- systems unlocked per Realm (charter 6.2, 11.2). A system whose tag is not unlocked is neither shown nor simulated.
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(System_Circulation, "Ascension.System.Circulation", "Q/E global aura rotation; CirculationSigned drives direction and strength (7.2). Realm 1.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(System_Pulse, "Ascension.System.Pulse", "Hold to charge, release an inward wave from AuraReach to the Dantian (7.3). Realm 1.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(System_Stability, "Ascension.System.Stability", "Aura coherence 0..1: below 0.7 weak Pulses, below 0.35 Rejection, at 0 Backlash (7.7). Realm 1.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(System_BasicMantra, "Ascension.System.BasicMantra", "The teaching Mantra: balanced, slightly faster Stability recovery, safest Auto (9.2). Realm 1.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(System_Purity, "Ascension.System.Purity", "Dantian contamination 0..1; Impure absorption lowers it, refinement raises it (7.8). Realm 2.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(System_RefinementPulse, "Ascension.System.RefinementPulse", "Charge to full then double-tap: drawn Impure becomes Pure at half Progress and a Stability cost (7.3). Realm 2.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(System_DantianCapacity, "Ascension.System.DantianCapacity", "The Dantian stores Qi up to the ladder row capacity; Qi Reserve is 60 percent of it (7.8). Realm 2.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(System_DaoUnlock, "Ascension.System.DaoUnlock", "The first Dao becomes selectable; the small generic Insight pool buys its first nodes (9.3). Realm 2.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(System_DensityLayers, "Ascension.System.DensityLayers", "Inner and outer aura density layers; an over-dense inner layer (above 0.9) rejects Qi (7.9). Realm 3.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(System_SecondMantraChoice, "Ascension.System.SecondMantraChoice", "A second Mantra becomes selectable (Stillness, Heavenly Light, Fire God) (9.2). Realm 3.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(System_DaoInsight, "Ascension.System.DaoInsight", "Dao-specific Insight is generated by absorbing the Dao natures and using its Techniques (9.3). Realm 3.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(System_AnchorDrift, "Ascension.System.AnchorDrift", "The body left in the world is affected by what happens inside: injury visuals on the Anchor (6.2, 7.12). Realm 3.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(System_Core, "Ascension.System.Core", "Golden Core: a persistent Dantian object with its own stability that can crack (6.2). Realm 4.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(System_CirculationMomentum, "Ascension.System.CirculationMomentum", "CirculationSigned persists between meditations at MomentumRetention 0.5 (7.2). Realm 4.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(System_Keystone, "Ascension.System.Keystone", "One identity-defining Dao node per Dao with a tradeoff (9.3). Realm 4.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(System_SplitCirculation, "Ascension.System.SplitCirculation", "Inner and outer layers rotate independently; the Layer Modifier drives the inner one (7.2). Realm 5.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(System_AutoFullEfficiency, "Ascension.System.AutoFullEfficiency", "Automatic cultivation runs at full efficiency while the player is present (6.2). Realm 5.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(System_ThirdMantraChoice, "Ascension.System.ThirdMantraChoice", "A third Mantra choice including Yin-Yang (9.2). Realm 5.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(System_CorruptedQi, "Ascension.System.CorruptedQi", "Corrupted condition: resistance 0.85, heavy drain, 3x Progress, corrupts the Core (7.5). Realm 6.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(System_DevouringMantra, "Ascension.System.DevouringMantra", "Demonic Devouring Mantra: Impure and Corrupted drawn faster, Purity loss doubled (9.2). Realm 6.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(System_DaoExpression, "Ascension.System.DaoExpression", "Dao Expression nodes that modify a Technique behaviour or visual (9.3). Realm 6.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(System_Domain, "Ascension.System.Domain", "The Cultivation Space itself becomes the aura: floor, horizon and sky follow the six parameters (7.9). Realm 7.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(System_RealmWaveLayers, "Ascension.System.RealmWaveLayers", "Realm-scale wave layers: Qi spawns to the horizon and approaches over multiple Pulses (7.9). Realm 7.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(System_DualMantra, "Ascension.System.DualMantra", "Two active Mantras with conflict rules (9.1). Realm 8.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(System_SecondKeystone, "Ascension.System.SecondKeystone", "A second Keystone may be taken (6.2). Realm 8.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(System_DaoResonance, "Ascension.System.DaoResonance", "Nodes in two Daos sharing a ResonanceTag interact; Overload above 1.0 causes Qi Deviation (9.5). Realm 8.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(System_AscensionPulse, "Ascension.System.AscensionPulse", "A field-wide contraction that consumes the Domain; used in the final Tribulation (7.3). Realm 9.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(System_FinalDaoNodes, "Ascension.System.FinalDaoNodes", "The deepest Dao nodes become available (6.2). Realm 9.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(System_Endgame, "Ascension.System.Endgame", "Endgame state: every action has a tenfold consequence; the ending is replayable at 9.9 (6.2, M7). Realm 9.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(System_Breakthrough, "Ascension.System.Breakthrough", "Minor Breakthrough: 3 s held charge, roll modified by Stability and Purity (6.4, 7.10). Realm 1.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(System_Tribulation, "Ascension.System.Tribulation", "Major Breakthrough: a 45-120 s scripted skill sequence with no random roll (6.5). Realm 1.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(System_AutoCultivation, "Ascension.System.AutoCultivation", "Low-attention mode driving the same input functions with conservative parameters (7.11). Realm 1.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(System_Techniques, "Ascension.System.Techniques", "Active abilities from Dao nodes in slots 1-4, demonstrated on the Resonance Stone (9.3, 9.6). Realm 2.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(System_LayerModifier, "Ascension.System.LayerModifier", "Hold to make Q/E drive the inner layer instead of the outer (8). Realm 5.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(System_DebugOverlay, "Ascension.System.DebugOverlay", "F1 overlay: every 7.1 and 7.4 number, the ladder row, RNG state, last 20 events (10.6). Always.");

	// Ascension.Qi.Condition.* -- behavioural identities of Qi (charter 7.5).
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Qi_Condition_Pure, "Ascension.Qi.Condition.Pure", "Baseline: smooth response, clean absorption, small Insight for its nature Dao (7.5).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Qi_Condition_Impure, "Ascension.Qi.Condition.Impure", "Resistance 0.7, drains Stability while Drawn, lowers Purity, 1.5x Progress; Rejected below Stability 0.35 (7.5).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Qi_Condition_Corrupted, "Ascension.Qi.Condition.Corrupted", "Realm 6+: resistance 0.85, heavy drain, large Purity loss, 3x Progress; corrupts the Core unless refined or devoured (7.5).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Qi_Condition_Refined, "Ascension.Qi.Condition.Refined", "Realm 8+: only from refining Pure Qi twice; resistance 0.05, no drain, 2x Progress, raises Stability on absorption (7.5).");

	// Ascension.Qi.Nature.* -- natures with one data-defined trait each (charter 7.6).
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Qi_Nature_Generic, "Ascension.Qi.Nature.Generic", "No trait; weight 1.0 at every Realm so it stays the plurality (7.6, D-0006). Realm 1.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Qi_Nature_Fire, "Ascension.Qi.Nature.Fire", "Higher Progress, raises Pressure while Drawn, drains Stability slightly (7.6). Realm 3.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Qi_Nature_Water, "Ascension.Qi.Nature.Water", "Lower Resistance, restores a little Stability on absorption (7.6). Realm 3.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Qi_Nature_Wood, "Ascension.Qi.Nature.Wood", "Left Free it slowly spawns a small second Wood wisp, capped (7.6). Realm 4.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Qi_Nature_Metal, "Ascension.Qi.Nature.Metal", "High Resistance, very high Progress; responds only to Pulses above 0.8 charge (7.6). Realm 4.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Qi_Nature_Earth, "Ascension.Qi.Nature.Earth", "Heavy: slow to draw but stabilises the aura while Drawn (7.6). Realm 5.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Qi_Nature_Yin, "Ascension.Qi.Nature.Yin", "Drawn faster by counterclockwise circulation; ambient at night (7.6, 7.13). Realm 2.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Qi_Nature_Yang, "Ascension.Qi.Nature.Yang", "Drawn faster by clockwise circulation; ambient by day (7.6, 7.13). Realm 2.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Qi_Nature_Life, "Ascension.Qi.Nature.Life", "Restores Purity on absorption (7.6). Realm 6.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Qi_Nature_Void, "Ascension.Qi.Nature.Void", "Temporarily reduces Reach on absorption but yields the largest Insight (7.6). Realm 7.");

	// Ascension.State.* -- aura, player, and wisp states published for Mantra conditions and UI (charter 7.1-7.12, 9.1, D-0013).
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_InWorld, "Ascension.State.InWorld", "The player is in the outer world; IMC_World is active (8, 10.1).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_Meditating, "Ascension.State.Meditating", "Consciousness is in the Cultivation Space; IMC_Cultivation is active (3.3, 10.2).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_Circulating_CW, "Ascension.State.Circulating.CW", "CirculationSigned above 0: clockwise global current; Yang is drawn faster (7.2, 7.6).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_Circulating_CCW, "Ascension.State.Circulating.CCW", "CirculationSigned below 0: counterclockwise global current; Yin is drawn faster (7.2, 7.6).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_CirculationHeld, "Ascension.State.CirculationHeld", "Both Q and E held: phase frozen, field dims, Stability recovers 50 percent faster (7.2).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_Pulse_Charging, "Ascension.State.Pulse.Charging", "Pulse input held; PulseCharge rises 0..1 over PulseChargeDuration and the field compresses (7.3).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_Pulse_Overcharging, "Ascension.State.Pulse.Overcharging", "Held past full by more than OverchargeGrace; Stability drains at OverchargeDrainRate and the ring reddens (7.3).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_Pulse_Releasing, "Ascension.State.Pulse.Releasing", "The inward wave is travelling from AuraReach to the centre over PulseFlashDuration (7.3).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_Pulse_Recovering, "Ascension.State.Pulse.Recovering", "PulseRecoveryDuration after release; new Pulses are blocked and the HUD reads Recovering (7.3).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_Pulse_Refining, "Ascension.State.Pulse.Refining", "A Refinement Pulse is in flight; wisps it draws are refined on absorption (7.3). Realm 2+.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_Breakthrough_Charging, "Ascension.State.Breakthrough.Charging", "Three-second held Breakthrough charge compressing the whole aura toward the Dantian (6.4).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_Breakthrough_Cooldown, "Ascension.State.Breakthrough.Cooldown", "A failed Breakthrough blocks re-attempts for BreakthroughCooldown, suggested 20 s (6.4).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_Tribulation_Warning, "Ascension.State.Tribulation.Warning", "Field darkens and the Dantian pulses; the player may still cancel at no cost (6.5).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_Tribulation_Trial, "Ascension.State.Tribulation.Trial", "Surges are active; meditation cannot be exited (6.5, 7.13).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_Tribulation_Resolution, "Ascension.State.Tribulation.Resolution", "The 5-8 s Major Breakthrough sequence, or Qi Deviation on failure (6.5).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_Backlash, "Ascension.State.Backlash", "Stability reached 0: aura collapse, Drawn wisps Rejected, Progress and Reserve lost, forced exit (7.12).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_BacklashRecovery, "Ascension.State.BacklashRecovery", "BacklashRecovery timer (60 s) after a Backlash; Stability recovery halved, injury visual on the Anchor (7.12).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_QiDeviation, "Ascension.State.QiDeviation", "Severe failure: dropped to Layer 1 of the Realm, Purity 0.3, Corruption applied, DeviationScar (7.12).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_AutoCultivating, "Ascension.State.AutoCultivating", "UAutoCultivationController is driving the aura input functions; HUD shows Auto-cultivating (7.11).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_Corrupted, "Ascension.State.Corrupted", "Corruption is applied to the Core; Pure Qi attraction is reduced until cleansed (7.5). Realm 6+.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_CoreCracked, "Ascension.State.CoreCracked", "The Core cracked at Purity 0; absorption halved until repaired by Pure Qi (6.2, 7.8). Realm 4+.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_DomainActive, "Ascension.State.DomainActive", "The Domain has replaced the flat disc; the space itself circulates (7.9). Realm 7+.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_ResonanceActive, "Ascension.State.ResonanceActive", "A Dao resonance pair is active and the Overload meter is building (9.5). Realm 8.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_Layer_Early, "Ascension.State.Layer.Early", "Layers 1-3 of a Realm; cosmetic grouping used by UI and Mantra conditions (6.1).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_Layer_Middle, "Ascension.State.Layer.Middle", "Layers 4-6 of a Realm (6.1).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_Layer_Late, "Ascension.State.Layer.Late", "Layers 7-9 of a Realm (6.1).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_Layer_Peak, "Ascension.State.Layer.Peak", "Layer 9; the next Breakthrough is a Tribulation (6.1).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_Stability_High, "Ascension.State.Stability.High", "Stability at or above 0.8; lets a Mantra condition express Stability above 0.8 (9.1, D-0013).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_Stability_Low, "Ascension.State.Stability.Low", "Stability below 0.5: Breakthrough chance heavily penalised; Auto pauses Pulses (7.7, D-0013).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_Stability_Critical, "Ascension.State.Stability.Critical", "Stability below 0.35: Impure Qi is Rejected on arrival; the field reddens (7.7, 10.3, D-0013).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_Purity_High, "Ascension.State.Purity.High", "Purity at or above 0.7; the threshold Auto mode waits for before a Breakthrough (7.11, D-0013).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_Purity_Low, "Ascension.State.Purity.Low", "Purity below 0.4: Pure Qi is attracted more weakly (7.8, D-0013).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_Density_InnerOverDense, "Ascension.State.Density.InnerOverDense", "InnerDensity above 0.9: incoming Qi is rejected until it decays (7.9). Realm 3+.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_Wisp_Free, "Ascension.State.Wisp.Free", "Wisp at rest in the field with only a bounded tangential drift, never an orbit (7.2, 7.4).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_Wisp_Drawn, "Ascension.State.Wisp.Drawn", "The wave front passed; moving inward on a decaying impulse; Impure drains Stability here (7.4, 7.5).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_Wisp_Absorbing, "Ascension.State.Wisp.Absorbing", "Reached the Dantian threshold; condensing while AbsorptionProgress fills (7.4).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_Wisp_Absorbed, "Ascension.State.Wisp.Absorbed", "Absorbed; Progress, Insight, Stability and Purity have been updated (3.3, 7.4).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_Wisp_Rejected, "Ascension.State.Wisp.Rejected", "Flung outward to 0.8 Reach with a visible burst and a Stability hit (7.5).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(State_Wisp_Refining, "Ascension.State.Wisp.Refining", "Being refined on absorption by a Refinement Pulse: Impure becomes Pure (7.3).");

	// Ascension.Event.* -- the last-20 event log and the determinism checksum (charter 10.6, 11.3).
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_EnterMeditation, "Ascension.Event.EnterMeditation", "Player entered the Cultivation Space (3.3, 10.2).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_ExitMeditation, "Ascension.Event.ExitMeditation", "Player returned to the body; autosave point (7.13, 10.7).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_CirculationStarted, "Ascension.Event.CirculationStarted", "CirculationSigned left zero (7.2).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_CirculationHeld, "Ascension.Event.CirculationHeld", "Both circulation inputs held; stillness began (7.2).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_PulseCharged, "Ascension.Event.PulseCharged", "PulseCharge reached 1.0 (7.3).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_PulseReleased, "Ascension.Event.PulseReleased", "Pulse released; Value carries ReleaseStrength (7.3).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_PulseOvercharged, "Ascension.Event.PulseOvercharged", "OverchargeGrace exceeded; Stability drain began (7.3).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_RefinementPulse, "Ascension.Event.RefinementPulse", "Double-tap at full charge fired a Refinement Pulse (7.3). Realm 2+.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_WispSpawned, "Ascension.Event.WispSpawned", "Ambient wisp faded in between 0.3 and 0.95 Reach (7.4).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_WispDrawn, "Ascension.Event.WispDrawn", "A wave front passed a wisp and it entered Drawn (7.3, 7.4).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_WispSettled, "Ascension.Event.WispSettled", "The impulse decayed and the wisp returned to Free (7.3).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_Absorbed, "Ascension.Event.Absorbed", "A wisp condensed at the Dantian; Value is the Progress granted (3.3, 7.4).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_Rejected, "Ascension.Event.Rejected", "A wisp was Rejected at the Dantian: Stability below RejectionThreshold or an over-dense inner layer (7.5, 7.9).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_Refined, "Ascension.Event.Refined", "An Impure wisp was refined to Pure on absorption (7.3).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_Transformed, "Ascension.Event.Transformed", "Impure Qi crossing the shear band became Pure under the Yin-Yang Mantra (9.2). Realm 5+.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_BreakthroughAttempt, "Ascension.Event.BreakthroughAttempt", "Breakthrough charge released; Value is the computed chance (6.4, 7.10).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_BreakthroughSuccess, "Ascension.Event.BreakthroughSuccess", "Layer advanced, aura re-expanded, Progress reset, Insight bonus granted (6.4).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_BreakthroughFailure, "Ascension.Event.BreakthroughFailure", "Progress and Stability dropped and the cooldown began; Message states why (6.4).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_TribulationStart, "Ascension.Event.TribulationStart", "Tribulation Warning phase began (6.5).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_TribulationSurge, "Ascension.Event.TribulationSurge", "A surge event fired; its warning was shown at least 1 s earlier (6.5, Appendix A).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_TribulationSuccess, "Ascension.Event.TribulationSuccess", "Trial success condition met (6.5).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_TribulationFailure, "Ascension.Event.TribulationFailure", "Trial failure condition met; Qi Deviation follows (6.5, 7.12).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_MajorBreakthrough, "Ascension.Event.MajorBreakthrough", "The 5-8 s resolution sequence played (6.5).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_RealmAdvance, "Ascension.Event.RealmAdvance", "Realm incremented to Layer 1 of the next Realm; new systems unlocked (6.2).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_Backlash, "Ascension.Event.Backlash", "Stability reached 0; Message names the cause (7.12).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_QiDeviation, "Ascension.Event.QiDeviation", "Severe failure state applied; Message names the cause (7.12).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_ScarCleared, "Ascension.Event.ScarCleared", "DeviationScar removed after one clean meditation: 10 Pure absorbed with no Rejection (7.12).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_CoreCracked, "Ascension.Event.CoreCracked", "The Core cracked at Purity 0 (7.8). Realm 4+.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_CoreRepaired, "Ascension.Event.CoreRepaired", "A cracked Core was repaired by Pure Qi (6.2). Realm 4+.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_CorruptionApplied, "Ascension.Event.CorruptionApplied", "Corruption applied to the Core (7.5). Realm 6+.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_CorruptionCleansed, "Ascension.Event.CorruptionCleansed", "Corruption removed by refinement, Cleanse, or Life Qi (7.5, 9.4).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_ResonanceOverload, "Ascension.Event.ResonanceOverload", "Overload reached 1.0; Qi Deviation unless resonance was broken (9.5). Realm 8.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_TechniqueUsed, "Ascension.Event.TechniqueUsed", "A slotted Dao Technique activated and Qi Reserve was spent (9.3).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_InsightGranted, "Ascension.Event.InsightGranted", "Dao Insight added; SubjectId is the Dao and Value the amount (9.3).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_AutoToggled, "Ascension.Event.AutoToggled", "Automatic cultivation toggled; Value 1 for on, 0 for off (7.11).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_Saved, "Ascension.Event.Saved", "Save written by autosave or to a manual slot (10.7).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Event_Loaded, "Ascension.Event.Loaded", "Save restored including the RNG seed and stream position (7.10, 10.7).");

	// Ascension.Mantra.* -- the eight Mantras and the Realm 8 conflict families (charter 9.1, 9.2).
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Mantra_Basic, "Ascension.Mantra.Basic", "Basic Cultivation Mantra: Breathe, circulate, gather. Balanced, slightly faster Stability recovery (9.2). Realm 1.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Mantra_Stillness, "Ascension.Mantra.Stillness", "Stillness Mantra: Held recovers Stability 3x and gently pulls Pure inward; Pulse 30 percent weaker (9.2). Realm 1, second choice at 3.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Mantra_HeavenlyLight, "Ascension.Mantra.HeavenlyLight", "Heavenly Light Mantra: Pure highlighted, +50 percent Insight from Pure, Impure repelled from the inner layer (9.2). Realm 3.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Mantra_FireGod, "Ascension.Mantra.FireGod", "Fire God Mantra: Pulse charges 40 percent faster, Fire 2x Progress, Stability drains while charging (9.2). Realm 3.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Mantra_YinYang, "Ascension.Mantra.YinYang", "Yin-Yang Mantra: while inner and outer layers oppose, Impure crossing the shear band becomes Pure (9.2). Realm 5.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Mantra_DemonicDevouring, "Ascension.Mantra.DemonicDevouring", "Demonic Devouring Mantra: Impure and Corrupted drawn faster, 3x Progress, Purity loss doubled (9.2). Realm 6.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Mantra_VoidStillness, "Ascension.Mantra.VoidStillness", "Void Stillness Mantra: Reach +50 percent, ambient +50 percent, Void safe, Pulse recovery doubled (9.2). Realm 7.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Mantra_Integration, "Ascension.Mantra.Integration", "Integration Mantra: second slot only; resolves the pair conflicts and enables Dao resonance (9.2). Realm 8.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Mantra_Conflict_Aggressive, "Ascension.Mantra.Conflict.Aggressive", "Dual-Mantra conflict family for pressure-driven Mantras; membership is set on UDA_Mantra ConflictTags (9.1). Realm 8.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Mantra_Conflict_Still, "Ascension.Mantra.Conflict.Still", "Dual-Mantra conflict family for stillness Mantras; membership is set on UDA_Mantra ConflictTags (9.1). Realm 8.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Mantra_Conflict_Demonic, "Ascension.Mantra.Conflict.Demonic", "Dual-Mantra conflict family for the Devouring path; membership is set on UDA_Mantra ConflictTags (9.1). Realm 8.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Mantra_Conflict_Void, "Ascension.Mantra.Conflict.Void", "Dual-Mantra conflict family for emptiness Mantras; membership is set on UDA_Mantra ConflictTags (9.1). Realm 8.");

	// Ascension.Dao.* -- the five Daos, node families, Techniques and Keystones (charter 9.3, 9.4, D-0014).
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Dao_Fire, "Ascension.Dao.Fire", "Dao of Fire (Fire, Yang): pressure, speed, risk; Keystone Furnace Heart (9.4).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Dao_Water, "Ascension.Dao.Water", "Dao of Water (Water, Yin): flow, recovery, safety; Keystone Deep Current (9.4).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Dao_Life, "Ascension.Dao.Life", "Dao of Life (Life, Wood): growth, Purity, patience; Keystone Rooted (9.4).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Dao_Sword, "Ascension.Dao.Sword", "Dao of the Sword (Metal, Generic): precision, timing; Keystone Single Stroke (9.4).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Dao_Void, "Ascension.Dao.Void", "Dao of the Void (Void, Generic): reach, emptiness, Insight; Keystone Boundless (9.4).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Dao_Node_Technique, "Ascension.Dao.Node.Technique", "Node family: grants an active ability in slots 1-4 (9.3).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Dao_Node_Expression, "Ascension.Dao.Node.Expression", "Node family: modifies a Technique behaviour or visual (9.3). Realm 6+.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Dao_Node_Principle, "Ascension.Dao.Node.Principle", "Node family: passive rule change (9.3).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Dao_Node_Insight, "Ascension.Dao.Node.Insight", "Node family (Cultivation Insight): improves interaction with a nature, Mantra, aura state or Realm system (9.3).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Dao_Node_Keystone, "Ascension.Dao.Node.Keystone", "Node family: one per Dao, identity-defining, with a tradeoff (9.3). Realm 4+.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Dao_Technique_EmberPulse, "Ascension.Dao.Technique.EmberPulse", "Dao of Fire: a mini-Pulse usable during recovery (9.4).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Dao_Technique_FlameCirculation, "Ascension.Dao.Technique.FlameCirculation", "Dao of Fire: temporarily doubles the circulation build rate (9.4).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Dao_Technique_StillPool, "Ascension.Dao.Technique.StillPool", "Dao of Water: instant Stability restore that costs Qi (9.4).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Dao_Technique_Tide, "Ascension.Dao.Technique.Tide", "Dao of Water: the next Pulse draws Qi in two waves (9.4).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Dao_Technique_Bloom, "Ascension.Dao.Technique.Bloom", "Dao of Life: Wood wisps multiply faster for a duration (9.4).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Dao_Technique_Cleanse, "Ascension.Dao.Technique.Cleanse", "Dao of Life: spend Qi to restore Purity (9.4).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Dao_Technique_Cut, "Ascension.Dao.Technique.Cut", "Dao of the Sword: a Pulse released within 0.1 s of full charge draws Metal Qi instantly (9.4).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Dao_Technique_Edge, "Ascension.Dao.Technique.Edge", "Dao of the Sword: one-shot; rejects all Impure Qi outward (9.4).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Dao_Technique_Expand, "Ascension.Dao.Technique.Expand", "Dao of the Void: Reach +100 percent for 10 s (9.4).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Dao_Technique_Silence, "Ascension.Dao.Technique.Silence", "Dao of the Void: all wisps freeze for 3 s (9.4).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Dao_Keystone_FurnaceHeart, "Ascension.Dao.Keystone.FurnaceHeart", "Fire Keystone: Stability drains constantly but every Pulse is a Refinement Pulse (9.4).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Dao_Keystone_DeepCurrent, "Ascension.Dao.Keystone.DeepCurrent", "Water Keystone: circulation never decays; braking costs Qi (9.4).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Dao_Keystone_Rooted, "Ascension.Dao.Keystone.Rooted", "Life Keystone: Auto mode runs at 100 percent efficiency; manual Pulse strength capped at 0.8 (9.4).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Dao_Keystone_SingleStroke, "Ascension.Dao.Keystone.SingleStroke", "Sword Keystone: instant Pulse charge, tripled recovery, Metal Qi 3x Progress (9.4).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Dao_Keystone_Boundless, "Ascension.Dao.Keystone.Boundless", "Void Keystone: Reach doubles permanently; Stability recovery halves (9.4).");

	// Ascension.Resonance.* -- Dao resonance families and the Overload meter (charter 9.5).
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Resonance_Flame, "Ascension.Resonance.Flame", "Resonance family of the Dao of Fire; a pair resonates when both Daos hold a node carrying this tag (9.5). Realm 8.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Resonance_Flow, "Ascension.Resonance.Flow", "Resonance family of the Dao of Water; a pair resonates when both Daos hold a node carrying this tag (9.5). Realm 8.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Resonance_Growth, "Ascension.Resonance.Growth", "Resonance family of the Dao of Life; a pair resonates when both Daos hold a node carrying this tag (9.5). Realm 8.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Resonance_Edge, "Ascension.Resonance.Edge", "Resonance family of the Dao of the Sword; a pair resonates when both Daos hold a node carrying this tag (9.5). Realm 8.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Resonance_Emptiness, "Ascension.Resonance.Emptiness", "Resonance family of the Dao of the Void; a pair resonates when both Daos hold a node carrying this tag (9.5). Realm 8.");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Resonance_Overload, "Ascension.Resonance.Overload", "The resonance Overload meter; above 1.0 it causes Qi Deviation unless broken by Circulation Held for 2 s (9.5). Realm 8.");

	// Ascension.Scar.* -- persistent failure states (charter 7.12, 7.5).
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Scar_Deviation, "Ascension.Scar.Deviation", "DeviationScar: halves Insight gain until one clean meditation of 10 Pure absorbed with no Rejection (7.12).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Scar_BacklashInjury, "Ascension.Scar.BacklashInjury", "Lingering injury after Backlash: dark vein overlay on the Anchor, Stability recovery halved for BacklashRecovery 60 s (7.12).");
	UE_DEFINE_GAMEPLAY_TAG_COMMENT(Scar_Corruption, "Ascension.Scar.Corruption", "Persistent Corruption on the Core: reduces Pure Qi attraction until cleansed (7.5). Realm 6+.");
}
